#novkovic

PATCH_WIDTH = 512
PATCH_HEIGHT = 384
PATCH_OVERLAP = 96

CONE_PATCH_PROBABILITY = 0.45

BATCH_SIZE = 4
EPOCHS = 30
LEARNING_RATE = 1e-4

VALIDATION_FRACTION = 0.20
RANDOM_SEED = 42

GEOMETRY_MIN_AREA_FOR_SHAPE = 40
MAX_CONE_WIDTH_HEIGHT_RATIO = 1.8
MAX_CONE_EXTENT = 0.85
MAX_COMPONENT_AREA_RATIO = 0.08