#novkovic

"""Configuration parameters for cone segmentation."""

RANDOM_SEED = 42

INPUT_HEIGHT = 128
INPUT_WIDTH = 128
INPUT_CHANNELS = 3

BASE_FILTERS = 16
DROPOUT_RATE = 0.20

VALIDATION_FRACTION = 0.20

BBOX_PADDING = 0.10
BBOX_PADDING_MIN = 0.10
BBOX_PADDING_MAX = 0.15
BBOX_CENTER_JITTER = 0.05

HORIZONTAL_FLIP_PROBABILITY = 0.50
MAX_ROTATION_DEGREES = 8.0

BRIGHTNESS_JITTER = 0.15
CONTRAST_JITTER = 0.15
SATURATION_JITTER = 0.10

LEARNING_RATE = 1e-3
BATCH_SIZE = 32
NUM_EPOCHS = 50